name: DropFloatingText
version: "1.1"
main: me.droptext.DropFloatingText
api-version: 1.21
author: notsads

commands:
  droptext:
    description: Reload DropFloatingText config
    usage: /droptext reload
    permission: droptext.admin

permissions:
  droptext.admin:
    default: op
